version: "3"
services:

    
    client:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house-frontend/client:latest
        restart: always
        ports:
            - 5000:8080
        networks:
            - frontend
            - backend

    management:
        image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house-frontend/management:latest
        restart: always
        ports:
            - 5001:4000
        networks:
            - backend
        depends_on:
            - statistics-service-db

    

networks:
    frontend:
    backend:

volumes:
    db-data:
