name: Build and Deploy dev client 
on: 
  push:
    paths:
      - 'src/client/**'
      - '.github/workflows/client.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build client
        run: docker build -f src/client/Dockerfile -t ${DOCKER_REG_URL}/${GITHUB_REPOSITORY}/client:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t ${DOCKER_REG_URL}/${GITHUB_REPOSITORY}/client:action-ci src/client

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login ${DOCKER_REG_URL} -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push client tag branch number
        run : docker push ${DOCKER_REG_URL}/${GITHUB_REPOSITORY}/client:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push client tag latest
        run: docker push ${DOCKER_REG_URL}/${GITHUB_REPOSITORY}/client:action-ci

  deploy-k8s-test-github:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
 
       - name: list env
         run: env && ls
 
       #- name: replace project name  
       #  run: sed -i "s|${DOCKER_REG_URL}\/idcf-boat-house\/boat-house-frontend|${DOCKER_REG_URL}\/${GITHUB_REPOSITORY%/*}\/boat-house-frontend|g" devops/kompose/test/client-*.yaml

       - name: replace github org name
         run: sed -i "s|#{BOATHOUSE_ORG_NAME}#|${GITHUB_REPOSITORY_OWNER}|g" devops/kompose/test/client-*.yaml

       - name: replace rep branch name
         run: sed -i "s|#{env.BRANCH_NAME}#|action-${GITHUB_REF##*/}-ci|g" devops/kompose/test/client-*.yaml

       - name: replace BUILD ID
         run: sed -i "s|#{env.BUILD_ID}#|${GITHUB_RUN_NUMBER}|g" devops/kompose/test/client-*.yaml

      #  - name: replace docker images tags
      #    run: sed -i "s|:latest$|:action-ci|g" devops/kompose/test/client-*.yaml 

       - name: replace k8s namespace
         run: sed -i "s|#{DEPLOY_K8S_NAMESPACE_TEST}#|${{ secrets.DEPLOY_K8S_NAMESPACE_TEST }}|g" devops/kompose/test/client-*.yaml


       - name: grep images url
         run: grep -i "image:" devops/kompose/test/client-*.yaml
         #run: ls kompose/test/client-*.yaml
 
       - uses: Azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}
 
       - uses: Azure/k8s-create-secret@v1
         with:
           namespace: boathouse-test-github
           container-registry-url: ${DOCKER_REG_URL}
           container-registry-username: ${GITHUB_REPOSITORY%/*}
           container-registry-password: ${{ secrets.packages_token }}
           secret-name: regcred
 
       - uses: Azure/k8s-deploy@v1
         with:
           namespace: 'boathouse-test-github'
           manifests: |
              devops/kompose/test/client-deployment.yaml
              devops/kompose/test/client-svc.yaml
           kubectl-version: 'latest'

