name: Build and Depoly dev management 
on: 
  push:
    paths:
      - 'src/management/**'
      - '.github/workflows/management.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build management
        run: docker build -f src/management/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-ci src/management

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push management tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push management tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-ci

  deploy-k8s-test-github:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: list env
         run: env && ls

       #- name: replace project name 
       #  run: sed -i "s|docker.pkg.github.com\/idcf-boat-house\/boat-house-frontend|docker.pkg.github.com\/${GITHUB_REPOSITORY%/*}\/boat-house-frontend|g" devops/kompose/test/client-*.yaml

       - name: replace github org name
         run: sed -i "s|#{BOATHOUSE_ORG_NAME}#|${GITHUB_REPOSITORY_OWNER}|g" devops/kompose/test/management-*.yaml

       - name: replace rep branch name
         run: sed -i "s|#{env.BRANCH_NAME}#|action-${GITHUB_REF##*/}-ci|g" devops/kompose/test/management-*.yaml

       - name: replace BUILD ID
         run: sed -i "s|#{env.BUILD_ID}#|${GITHUB_RUN_NUMBER}|g" devops/kompose/test/management-*.yaml

      #  - name: replace docker images tags
      #    run: sed -i "s|:latest$|:action-ci|g" devops/kompose/test/management-*.yaml 

       - name: replace k8s namespace
         run: sed -i "s|#{DEPLOY_K8S_NAMESPACE_TEST}#|${{ secrets.DEPLOY_K8S_NAMESPACE_TEST }}|g" devops/kompose/test/management-*.yaml


       - name: grep images url
         run: grep -i "image:" devops/kompose/test/management-*.yaml
         #run: ls devops/kompose/test/management-*.yaml

       - uses: Azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}

       - uses: Azure/k8s-create-secret@v1
         with:
           container-registry-url: docker.pkg.github.com
           container-registry-username: ${GITHUB_REPOSITORY%/*}
           container-registry-password: ${{ secrets.packages_token }}
           secret-name: demo-k8s-secret

       - uses: Azure/k8s-deploy@v1
         with:
           namespace: 'boathouse-test-github'
           manifests: |
              devops/kompose/test/management-deployment.yaml
              devops/kompose/test/management-svc.yaml
           kubectl-version: 'latest'
